config/routes.rb
Reports::Application.routes.draw do

  get "help/index"

  get "orders/payment"
  get "clients/clients_to_excel_format"
  get "orders/orders_to_excel_format"
  get "outlays/outlays_to_excel_format"
  get "salaries/salaries_to_excel_format"
  get "msalaries/msalaries_to_excel_format"
  get "payments/payments_to_excel_format"
  get "statuses/statuses_to_excel_format"
  get "resources/districts_to_excel_format"
  get "channels/channels_to_excel_format"
  get "courses/courses_to_excel_format"
  get "costs/costs_to_excel_format"
  get "offices/offices_to_excel_format"
  get "managers/managers_to_excel_format"
  get "teachers/teachers_to_excel_format"
  get "schedules/schedules_to_excel_format"
  get "objects_of_expenditures/obj_of_expend_to_excel_format"

  post "clients/sort_options"
  post "orders/sort_options"
  post "outlays/sort_options"
  post "salaries/sort_options"
  post "msalaries/sort_options"
  post "payments/sort_options"
  post "salaries/:id/edit" => 'salaries#edit'
  post "salaries/:id/schedules" => 'salaries#schedules'
  post "payments/new"
  post "salaries/new"

  post "salaries/salary_search_options"
  post "/salary_search_options" =>  'salaries#salary_search_options'
  post "salaries/:id/salary_search_options" => 'salaries#salary_search_options'

  post "orders/search_optionss"
  post "/search_optionss" =>  'orders#search_optionss'
  post "orders/:id/search_optionss" => 'orders#search_optionss'

  post "payments/search_options"
  post "/search_options" =>  'payments#search_options'
  post "payments/:id/search_options" => 'payments#search_options'

  resources :outlays

  resources :msalaries

  resources :managers

  resources :salaries

  resources :teachers

  resources :schedules

  resources :payments

  resources :orders

  resources :offices

  resources :clients

  resources :costs

  resources :courses

  resources :channels

  resources :resources

  resources :help

  resources :objects_of_expenditures

  resources :mail_boxes

  resources :periods

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :users do 
    member do
      get 'change_user'
      get 'ban'
    end

    collection do
      get 'list'
    end
  end

  resources :statuses
  match 'orders/payment', to: 'orders#payment', as: :payment_to_order
  match 'clients/clients_to_excel_format', to: 'clients#clients_to_excel_format', as: :clients_to_xls
  match 'orders/orders_to_excel_format', to: 'orders#orders_to_excel_format', as: :orders_to_xls
  match 'outlays/outlays_to_excel_format', to: 'outlays#outlays_to_excel_format', as: :outlays_to_xls
  match 'salaries/salaries_to_excel_format', to: 'salaries#salaries_to_excel_format', as: :salaries_to_xls
  match 'msalaries/msalaries_to_excel_format', to: 'msalaries#msalaries_to_excel_format', as: :msalaries_to_xls
  match 'payments/payments_to_excel_format', to: 'payments#payments_to_excel_format', as: :payments_to_xls
  match 'statuses/statuses_to_excel_format', to: 'statuses#statuses_to_excel_format', as: :statuses_to_xls
  match 'resources/resources_to_excel_format', to: 'resources#resources_to_excel_format', as: :resources_to_xls
  match 'channels/channels_to_excel_format', to: 'channels#channels_to_excel_format', as: :channels_to_xls
  match 'courses/courses_to_excel_format', to: 'courses#courses_to_excel_format', as: :courses_to_xls
  match 'costs/costs_to_excel_format', to: 'costs#costs_to_excel_format', as: :costs_to_xls
  match 'offices/offices_to_excel_format', to: 'offices#offices_to_excel_format', as: :offices_to_xls
  match 'managers/managers_to_excel_format', to: 'managers#managers_to_excel_format', as: :managers_to_xls
  match 'teachers/teachers_to_excel_format', to: 'teachers#teachers_to_excel_format', as: :teachers_to_xls
  match 'schedules/schedules_to_excel_format', to: 'schedules#schedules_to_excel_format', as: :schedules_to_xls
  match 'resources/districts_to_excel_format', to: 'resources#districts_to_excel_format', as: :district_to_xls
  match 'objects_of_expenditures/obj_of_expend_to_excel_format', to: 'objects_of_expenditures#obj_of_expend_to_excel_format', as: :obj_of_expend_to_xls

  match 'help/admin_add_user', to: 'help#admin_add_user', as: :add_user

  match 'users/create', to: 'users#create', as: :create_user

  match 'help', to: 'help#index', as: :help_page

  root :to => 'clients#index'

end

app/models/office.rb
class Office < ActiveRecord::Base
	has_many :clients
	has_many :orders
	has_many :schedules

  validates :name, :address, presence:true

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      each do |office|
        csv << office.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/offices_controller.rb
# -*- encoding : utf-8 -*-
class OfficesController < ApplicationController
  # GET /offices
  # GET /offices.json
  before_filter :only_admin_and_user, only: [:destroy, :edit, :update, :new, :create]
  def index
    if params[:id].present?
      @office = Office.find_by_id(params[:id])
    end
    @offices = Office.order(:created_at).reverse_order.page(params[:page]).per(50)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @offices }
      format.js
    end
  end

  # GET /offices/1
  # GET /offices/1.json
  def show
    @office = Office.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @office }
    end
  end

  # GET /offices/new
  # GET /offices/new.json
  def new
    @office = Office.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @office }
    end
  end

  # GET /offices/1/edit
  def edit
    @office = Office.find(params[:id])
  end

  # POST /offices
  # POST /offices.json
  def create
    @office = Office.new(params[:office])

    respond_to do |format|
      if @office.save
        format.html { redirect_to @office, notice: 'Office was successfully created.' }
        format.json { render json: @office, status: :created, location: @office }
      else
        format.html { render action: "new" }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /offices/1
  # PUT /offices/1.json
  def update
    @office = Office.find(params[:id])

    respond_to do |format|
      if @office.update_attributes(params[:office])
        format.html { redirect_to @office, notice: 'Office was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offices/1
  # DELETE /offices/1.json
  def destroy
    @office = Office.find(params[:id])
    @office.destroy

    respond_to do |format|
      format.html { redirect_to offices_url }
      format.json { head :no_content }
    end
  end

  def offices_to_excel_format
    @offices = Office.all
    respond_to do |format|
      format.html
      format.csv { send_data @offices.to_csv }
      format.xls
    end
  end

end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/views/offices/_form.html.erb
<div class="form-wrap clearfix">
  <h1><%= action_name == 'edit' ? 'Редактирование офиса' : 'Новый офис'%></h1>
  <hr>
  <%= flash[:notice]%>
<%= simple_form_for(@office) do |f| %>
  <%= f.input :name, label: "Название" %>
  <%= f.input :address, label: "Адрес" %>
  <%= f.input :phone, label: "Телефон" %>
    <div id="submit">
      <%= f.button :submit, :value => "Сохранить"%>
      <div>
        <%= link_to 'К списку', offices_path, class: "btn"%>
      </div>
    </div>
<% end %>
</div>

app/views/offices/_modal.html.erb
<p>
  <b>Название:</b>
  <%= @office.name %>
</p>

<p>
  <b>Адрес:</b>
  <%= @office.address %>
</p>

<p>
  <b>Телефон:</b>
  <%= @office.phone %>
</p>

app/views/offices/edit.html.erb
<%= render 'form' %>

app/views/offices/index.html.erb
<div class='table-actions'>
  <h1 class='page-title'>Офисы</h1>
  <ul class='create-download'>
    <% if user_role != "visitor" %>
        <li>
          <%= link_to new_office_path do %>
              <i class='icon-plus-sign icon-2x'></i>
          <% end %>
        </li>
    <% end %>
    <li>
      <%= link_to offices_to_xls_path + ".xls" do %>
          <i class='icon-save icon-2x'></i>
      <% end %>
    </li>
  </ul>
  <% if flash[:notice] %>
      <span style="color: #41b140;"><%= flash[:notice] %></span>
  <% end %>
  <hr>
  <%= paginate @offices, :window => 2 %>
</div>

<table id="demotable" class="table table-striped">
  <thead>
  <tr class="sort">
    <th class='record-manipulate'></th>
    <th>Название</th>
    <th>Адрес</th>
    <th>Телефон</th>
  </tr>
  </thead>

  <tbody>
<% @offices.each do |office| %>
  <tr>
    <td class="manipulate-box">
      <ul>
        <li><%= link_to url_for(id: office, anchor: 'myModal'), {:remote => true, 'data-toggle'=>"modal"} do%> <i class="icon-search"></i>
          <% end %></li>
        <% if user_role != "visitor" %>
            <li><%= link_to edit_office_path(office) do %> <i class="icon-pencil"></i>
              <% end %></li>
            <li><%= link_to office, confirm: 'Вы уверены?', method: :delete do %>
                  <i class="icon-trash"></i>
              <% end %></li>
        <% end %>
      </ul>
    </td>
    <td><%= office.name %></td>
    <td><%= office.address %></td>
    <td><%= office.phone %></td>
  </tr>
<% end %>
  </tbody>
</table>

<!-- Modal -->
<%= set_modal_window %>

app/views/offices/index.js.erb
$('#myModalLabel').html("Офис");
$('.modal-body p').html("<%=j render partial: 'modal' %>");

app/views/offices/new.html.erb
<%= render 'form' %>

app/views/offices/offices_to_excel_format.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:x="urn:schemas-microsoft-com:office:excel"
          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">название</Data></Cell>
        <Cell><Data ss:Type="String">адрес</Data></Cell>
        <Cell><Data ss:Type="String">телефон</Data></Cell>
      </Row>
      <% @offices.each do |office| %>
          <Row>
            <Cell><Data ss:Type="Number"><%= office.id %></Data></Cell>
            <Cell><Data ss:Type="String"><%= office.name %></Data></Cell>
            <Cell><Data ss:Type="String"><%= office.address %></Data></Cell>
            <Cell><Data ss:Type="String"><%= office.phone %></Data></Cell>
          </Row>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/offices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>название:</b>
  <%= @office.name %>
</p>

<p>
  <b>адрес:</b>
  <%= @office.address %>
</p>

<p>
  <b>телефон:</b>
  <%= @office.phone %>
</p>


<%= link_to 'редактирование', edit_office_path(@office) %> |
<%= link_to 'к списку', offices_path %>