config/routes.rb
Reports::Application.routes.draw do

  get "help/index"

  get "orders/payment"
  get "clients/clients_to_excel_format"
  get "orders/orders_to_excel_format"
  get "outlays/outlays_to_excel_format"
  get "salaries/salaries_to_excel_format"
  get "msalaries/msalaries_to_excel_format"
  get "payments/payments_to_excel_format"
  get "statuses/statuses_to_excel_format"
  get "resources/districts_to_excel_format"
  get "channels/channels_to_excel_format"
  get "courses/courses_to_excel_format"
  get "costs/costs_to_excel_format"
  get "offices/offices_to_excel_format"
  get "managers/managers_to_excel_format"
  get "teachers/teachers_to_excel_format"
  get "schedules/schedules_to_excel_format"
  get "objects_of_expenditures/obj_of_expend_to_excel_format"

  post "clients/sort_options"
  post "orders/sort_options"
  post "outlays/sort_options"
  post "salaries/sort_options"
  post "msalaries/sort_options"
  post "payments/sort_options"
  post "salaries/:id/edit" => 'salaries#edit'
  post "salaries/:id/schedules" => 'salaries#schedules'
  post "payments/new"
  post "salaries/new"

  post "salaries/salary_search_options"
  post "/salary_search_options" =>  'salaries#salary_search_options'
  post "salaries/:id/salary_search_options" => 'salaries#salary_search_options'

  post "orders/search_optionss"
  post "/search_optionss" =>  'orders#search_optionss'
  post "orders/:id/search_optionss" => 'orders#search_optionss'

  post "payments/search_options"
  post "/search_options" =>  'payments#search_options'
  post "payments/:id/search_options" => 'payments#search_options'

  resources :outlays

  resources :msalaries

  resources :managers

  resources :salaries

  resources :teachers

  resources :schedules

  resources :payments

  resources :orders

  resources :offices

  resources :clients

  resources :costs

  resources :courses

  resources :channels

  resources :resources

  resources :help

  resources :objects_of_expenditures

  resources :mail_boxes

  resources :periods

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :users do 
    member do
      get 'change_user'
      get 'ban'
    end

    collection do
      get 'list'
    end
  end

  resources :statuses
  match 'orders/payment', to: 'orders#payment', as: :payment_to_order
  match 'clients/clients_to_excel_format', to: 'clients#clients_to_excel_format', as: :clients_to_xls
  match 'orders/orders_to_excel_format', to: 'orders#orders_to_excel_format', as: :orders_to_xls
  match 'outlays/outlays_to_excel_format', to: 'outlays#outlays_to_excel_format', as: :outlays_to_xls
  match 'salaries/salaries_to_excel_format', to: 'salaries#salaries_to_excel_format', as: :salaries_to_xls
  match 'msalaries/msalaries_to_excel_format', to: 'msalaries#msalaries_to_excel_format', as: :msalaries_to_xls
  match 'payments/payments_to_excel_format', to: 'payments#payments_to_excel_format', as: :payments_to_xls
  match 'statuses/statuses_to_excel_format', to: 'statuses#statuses_to_excel_format', as: :statuses_to_xls
  match 'resources/resources_to_excel_format', to: 'resources#resources_to_excel_format', as: :resources_to_xls
  match 'channels/channels_to_excel_format', to: 'channels#channels_to_excel_format', as: :channels_to_xls
  match 'courses/courses_to_excel_format', to: 'courses#courses_to_excel_format', as: :courses_to_xls
  match 'costs/costs_to_excel_format', to: 'costs#costs_to_excel_format', as: :costs_to_xls
  match 'offices/offices_to_excel_format', to: 'offices#offices_to_excel_format', as: :offices_to_xls
  match 'managers/managers_to_excel_format', to: 'managers#managers_to_excel_format', as: :managers_to_xls
  match 'teachers/teachers_to_excel_format', to: 'teachers#teachers_to_excel_format', as: :teachers_to_xls
  match 'schedules/schedules_to_excel_format', to: 'schedules#schedules_to_excel_format', as: :schedules_to_xls
  match 'resources/districts_to_excel_format', to: 'resources#districts_to_excel_format', as: :district_to_xls
  match 'objects_of_expenditures/obj_of_expend_to_excel_format', to: 'objects_of_expenditures#obj_of_expend_to_excel_format', as: :obj_of_expend_to_xls

  match 'help/admin_add_user', to: 'help#admin_add_user', as: :add_user

  match 'users/create', to: 'users#create', as: :create_user

  match 'help', to: 'help#index', as: :help_page

  root :to => 'clients#index'

end

app/models/cost.rb
class Cost < ActiveRecord::Base
	has_many :outpays
  validates :name, presence:true

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      each do |cost|
        csv << cost.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/costs_controller.rb
# -*- encoding : utf-8 -*-
class CostsController < ApplicationController
  # GET /costs
  # GET /costs.json
  before_filter :only_admin_and_user, only: [:destroy, :edit, :update, :new, :create]
  def index
    if params[:id].present?
      @cost = Cost.find_by_id(params[:id])
    end
    @costs = Cost.order(:created_at).reverse_order.page(params[:page]).per(50)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @costs }
      format.js
    end
  end

  # GET /costs/1
  # GET /costs/1.json
  def show
    @cost = Cost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cost }
    end
  end

  # GET /costs/new
  # GET /costs/new.json
  def new
    @cost = Cost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cost }
    end
  end

  # GET /costs/1/edit
  def edit
    @cost = Cost.find(params[:id])
  end

  # POST /costs
  # POST /costs.json
  def create
    @cost = Cost.new(params[:cost])

    respond_to do |format|
      if @cost.save
        format.html { redirect_to @cost, notice: 'Cost was successfully created.' }
        format.json { render json: @cost, status: :created, location: @cost }
      else
        format.html { render action: "new" }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /costs/1
  # PUT /costs/1.json
  def update
    @cost = Cost.find(params[:id])

    respond_to do |format|
      if @cost.update_attributes(params[:cost])
        format.html { redirect_to @cost, notice: 'Cost was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /costs/1
  # DELETE /costs/1.json
  def destroy
    @cost = Cost.find(params[:id])
    @cost.destroy

    respond_to do |format|
      format.html { redirect_to costs_url }
      format.json { head :no_content }
    end
  end

  def costs_to_excel_format
    @costs = Cost.all
    respond_to do |format|
      format.html
      format.csv { send_data @costs.to_csv }
      format.xls
    end
  end

end

app/helpers/costs_helper.rb
module CostsHelper
end

app/views/costs/_form.html.erb
<div class="form-wrap clearfix">
  <h1><%= action_name == 'edit' ? 'Редактирование типа расходов' : 'Новый тип расходов'%></h1>
  <hr>
  <%= flash[:notice]%>
<%= simple_form_for(@cost) do |f| %>
    <%= f.input :name, label: "Имя" %>
    <div id="submit">
      <%= f.button :submit, :value => "Сохранить"%>
      <div>
        <%= link_to 'К списку', costs_path, class: "btn"%>
      </div>
    </div>
<% end %>
</div>

app/views/costs/_modal.html.erb
<p>
  <b>Имя:</b>
  <%= @cost.name %>
</p>

app/views/costs/costs_to_excel_format.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:x="urn:schemas-microsoft-com:office:excel"
          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">название</Data></Cell>
        <Cell><Data ss:Type="String">дата создания</Data></Cell>
        <Cell><Data ss:Type="String">дата обновления</Data></Cell>
      </Row>
      <% @costs.each do |cost| %>
          <Row>
            <Cell><Data ss:Type="Number"><%= cost.id %></Data></Cell>
            <Cell><Data ss:Type="String"><%= cost.name %></Data></Cell>
            <Cell><Data ss:Type="String"><%= cost.created_at.strftime("%d.%m.%Y") %></Data></Cell>
            <Cell><Data ss:Type="String"><%= cost.updated_at.strftime("%d.%m.%Y") %></Data></Cell>
          </Row>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/costs/edit.html.erb
<%= render 'form' %>

app/views/costs/index.html.erb
<div class='table-actions'>
  <h1 class='page-title'>Типы расходов</h1>
  <ul class='create-download'>
    <% if user_role != "visitor" %>
        <li>
          <%= link_to new_cost_path do %>
              <i class='icon-plus-sign icon-2x'></i>
          <% end %>
        </li>
    <% end %>
    <li>
      <%= link_to costs_to_xls_path + ".xls" do %>
          <i class='icon-save icon-2x'></i>
      <% end %>
    </li>
  </ul>
  <% if flash[:notice] %>
      <span style="color: #41b140;"><%= flash[:notice] %></span>
  <% end %>
  <hr>
  <%= paginate @costs, :window => 2 %>
</div>

<table id="demotable" class="table table-striped">
  <thead>
  <tr class="sort">
    <th class='record-manipulate'></th>
    <th>Название</th>
  </tr>
  </thead>
  <tbody>

<% @costs.each do |cost| %>
  <tr>
    <td class="manipulate-box">
      <ul>
        <li><%= link_to url_for(id: cost, anchor: 'myModal'), {:remote => true, 'data-toggle'=>"modal"} do%><i class="icon-search"></i>
          <% end %></li>
        <% if user_role != "visitor" %>
            <li><%= link_to edit_cost_path(cost) do %> <i class="icon-pencil"></i>
              <% end %></li>
            <li><%= link_to cost, confirm: 'Вы уверены?', method: :delete do %>
                  <i class="icon-trash"></i>
              <% end %></li>
        <% end %>
      </ul>
    </td>
    <td><%= cost.name %></td>
  </tr>
<% end %>
  </tbody>
</table>

<!-- Modal -->
<%= set_modal_window %>

app/views/costs/index.js.erb
$('#myModalLabel').html("Тип расходов");
$('.modal-body p').html("<%=j render partial: 'modal' %>");

app/views/costs/new.html.erb
<%= render 'form' %>

app/views/costs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>имя:</b>
  <%= @cost.name %>
</p>


<%= link_to 'ред.', edit_cost_path(@cost) %> |
<%= link_to 'к списку', costs_path %>