config/routes.rb
Reports::Application.routes.draw do

  get "help/index"

  get "orders/payment"
  get "clients/clients_to_excel_format"
  get "orders/orders_to_excel_format"
  get "outlays/outlays_to_excel_format"
  get "salaries/salaries_to_excel_format"
  get "msalaries/msalaries_to_excel_format"
  get "payments/payments_to_excel_format"
  get "statuses/statuses_to_excel_format"
  get "resources/districts_to_excel_format"
  get "channels/channels_to_excel_format"
  get "courses/courses_to_excel_format"
  get "costs/costs_to_excel_format"
  get "offices/offices_to_excel_format"
  get "managers/managers_to_excel_format"
  get "teachers/teachers_to_excel_format"
  get "schedules/schedules_to_excel_format"
  get "objects_of_expenditures/obj_of_expend_to_excel_format"

  post "clients/sort_options"
  post "orders/sort_options"
  post "outlays/sort_options"
  post "salaries/sort_options"
  post "msalaries/sort_options"
  post "payments/sort_options"
  post "salaries/:id/edit" => 'salaries#edit'
  post "salaries/:id/schedules" => 'salaries#schedules'
  post "payments/new"
  post "salaries/new"

  post "salaries/salary_search_options"
  post "/salary_search_options" =>  'salaries#salary_search_options'
  post "salaries/:id/salary_search_options" => 'salaries#salary_search_options'

  post "orders/search_optionss"
  post "/search_optionss" =>  'orders#search_optionss'
  post "orders/:id/search_optionss" => 'orders#search_optionss'

  post "payments/search_options"
  post "/search_options" =>  'payments#search_options'
  post "payments/:id/search_options" => 'payments#search_options'

  resources :outlays

  resources :msalaries

  resources :managers

  resources :salaries

  resources :teachers

  resources :schedules

  resources :payments

  resources :orders

  resources :offices

  resources :clients

  resources :costs

  resources :courses

  resources :channels

  resources :resources

  resources :help

  resources :objects_of_expenditures

  resources :mail_boxes

  resources :periods

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :users do 
    member do
      get 'change_user'
      get 'ban'
    end

    collection do
      get 'list'
    end
  end

  resources :statuses
  match 'orders/payment', to: 'orders#payment', as: :payment_to_order
  match 'clients/clients_to_excel_format', to: 'clients#clients_to_excel_format', as: :clients_to_xls
  match 'orders/orders_to_excel_format', to: 'orders#orders_to_excel_format', as: :orders_to_xls
  match 'outlays/outlays_to_excel_format', to: 'outlays#outlays_to_excel_format', as: :outlays_to_xls
  match 'salaries/salaries_to_excel_format', to: 'salaries#salaries_to_excel_format', as: :salaries_to_xls
  match 'msalaries/msalaries_to_excel_format', to: 'msalaries#msalaries_to_excel_format', as: :msalaries_to_xls
  match 'payments/payments_to_excel_format', to: 'payments#payments_to_excel_format', as: :payments_to_xls
  match 'statuses/statuses_to_excel_format', to: 'statuses#statuses_to_excel_format', as: :statuses_to_xls
  match 'resources/resources_to_excel_format', to: 'resources#resources_to_excel_format', as: :resources_to_xls
  match 'channels/channels_to_excel_format', to: 'channels#channels_to_excel_format', as: :channels_to_xls
  match 'courses/courses_to_excel_format', to: 'courses#courses_to_excel_format', as: :courses_to_xls
  match 'costs/costs_to_excel_format', to: 'costs#costs_to_excel_format', as: :costs_to_xls
  match 'offices/offices_to_excel_format', to: 'offices#offices_to_excel_format', as: :offices_to_xls
  match 'managers/managers_to_excel_format', to: 'managers#managers_to_excel_format', as: :managers_to_xls
  match 'teachers/teachers_to_excel_format', to: 'teachers#teachers_to_excel_format', as: :teachers_to_xls
  match 'schedules/schedules_to_excel_format', to: 'schedules#schedules_to_excel_format', as: :schedules_to_xls
  match 'resources/districts_to_excel_format', to: 'resources#districts_to_excel_format', as: :district_to_xls
  match 'objects_of_expenditures/obj_of_expend_to_excel_format', to: 'objects_of_expenditures#obj_of_expend_to_excel_format', as: :obj_of_expend_to_xls

  match 'help/admin_add_user', to: 'help#admin_add_user', as: :add_user

  match 'users/create', to: 'users#create', as: :create_user

  match 'help', to: 'help#index', as: :help_page

  root :to => 'clients#index'

end

app/models/teacher.rb
# -*- encoding : utf-8 -*-
class Teacher < ActiveRecord::Base
	has_and_belongs_to_many :courses
	has_many :orders
	has_many :schedules
	has_many :salaries

  validate :has_courses?



  validates :name, :surname, :phone, :courses, presence:true

  validates :email,
            :format => {:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i},
            :allow_blank => true



  def has_courses?
    errors[:base] << "Поле 'курс' не может быть пустым" if self.courses.blank?
  end

  def fio
    "#{self.try(:name)} #{self.try(:surname)}"
  end

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      each do |teacher|
        csv << teacher.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/teachers_controller.rb
# -*- encoding : utf-8 -*-
class TeachersController < ApplicationController
  # GET /teachers
  # GET /teachers.json
  before_filter :only_admin_and_user, only: [:destroy, :edit, :update, :new, :create]
  def index
    if params[:id].present?
      @teacher = Teacher.find_by_id(params[:id])
    end
    @teachers = Teacher.order(:created_at).reverse_order.page(params[:page]).per(50)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @teachers }
      format.js
    end
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
    @teacher = Teacher.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @teacher }
    end
  end

  # GET /teachers/new
  # GET /teachers/new.json
  def new
    @teacher = Teacher.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @teacher }
    end
  end

  # GET /teachers/1/edit
  def edit
    @teacher = Teacher.find(params[:id])
    
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(params[:teacher])

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render json: @teacher, status: :created, location: @teacher }
      else
        format.html { render action: "new" }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /teachers/1
  # PUT /teachers/1.json
  def update
    @teacher = Teacher.find(params[:id])

    respond_to do |format|
      if @teacher.update_attributes(params[:teacher])
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher = Teacher.find(params[:id])
    @teacher.destroy

    respond_to do |format|
      format.html { redirect_to teachers_url }
      format.json { head :no_content }
    end
  end

  def teachers_to_excel_format
    @teachers = Teacher.all
    respond_to do |format|
      format.html
      format.csv { send_data @teachers.to_csv }
      format.xls
    end
  end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<div class="form-wrap clearfix">
  <h1><%= action_name == 'edit' ? 'Редактирование преподавателя' : 'Новый преподаватель'%></h1>
  <hr>
  <%= flash[:notice]%>
<%= simple_form_for(@teacher) do |f| %>

  <%= f.input :surname, label: "Фамилия" %>
  <%= f.input :name, label: "Имя" %>
  <%= f.input :phone, label: "Телефон" %>
  <%= f.input :email %>
  <%= f.input :idvk, :label => "ID-VK" %>
  <%= f.input :workplace, label: "Рабочее место" %>
  <%= f.input :comment, label: "Комментарий", :input_html => { :cols => 50, :rows => 4 }  %>
  <%= f.association :courses, label: "Курс" %>
    <%= f.input :salary, label: "Оклад" %>
    <%= f.input :percent, label: "Процент" %>
    <div id="submit">
      <%= f.button :submit, :value => "Сохранить"%>
      <div>
        <%= link_to 'К списку', teachers_path, class: "btn"%>
      </div>
    </div>
<% end %>
</div>

app/views/teachers/_modal.html.erb
<p>
  <b>Фамилия:</b>
  <%= @teacher.surname %>
</p>
<p>
  <b>Имя:</b>
  <%= @teacher.name %>
</p>

<p>
  <b>Телефон:</b>
  <%= @teacher.phone %>
</p>

<p>
  <b>Email:</b>
  <%= @teacher.email %>
</p>

<p>
  <b>ID-VK:</b>
  <%= @teacher.idvk %>
</p>

<p>
  <b>Рабочее место:</b>
  <%= @teacher.workplace %>
</p>

<p>
  <b>Коммент:</b>
  <%= @teacher.comment %>
</p>

<p>
  <b>Курсы:</b>
  <% @teacher.courses.each do |x| %>
      <%=  x.name + ", " %>
  <% end %>
</p>

<p>
  <b>Оклад:</b>
  <%= @teacher.salary %>
</p>

<p>
  <b>Оклад:</b>
  <%= @teacher.percent %>
</p>

app/views/teachers/edit.html.erb
<%= render 'form' %>

app/views/teachers/index.html.erb
<div class='table-actions'>
  <h1 class='page-title'>Преподаватели</h1>
  <ul class='create-download'>
    <% if user_role != "visitor" %>
        <li>
          <%= link_to new_teacher_path do %>
              <i class='icon-plus-sign icon-2x'></i>
          <% end %>
        </li>
    <% end %>
    <li>
      <%= link_to teachers_to_xls_path + ".xls" do %>
          <i class='icon-save icon-2x'></i>
      <% end %>
    </li>
  </ul>
  <% if flash[:notice] %>
      <span style="color: #41b140;"><%= flash[:notice] %></span>
  <% end %>
  <hr>
  <%= paginate @teachers, :window => 2 %>
</div>

<table id="demotable" class="table table-striped">
  <thead>
    <tr class="sort">
      <th class='record-manipulate'></th>
      <th><div id="result" style="text-align: center; color: #000000;"></div>ФИО</th>
      <th>Телефон</th>
      <th>Курсы</th>
      <th>Email</th>
      <th>ID-VK</th>
      <th>Рабочее место</th>
      <th>Комментарий</th>
      <th>Оклад</th>
      <th>Процент</th>
    </tr>
  </thead>
  <tbody>
    <% @teachers.each do |teacher| %>
      <tr class="tr">
        <td class="manipulate-box">
          <ul>
            <li><%= link_to url_for(id: teacher, anchor: 'myModal'), {:remote => true, 'data-toggle'=>"modal"} do%> <i class="icon-search"></i>
              <% end %></li>
            <% if user_role != "visitor" %>
                <li><%= link_to edit_teacher_path(teacher) do %> <i class="icon-pencil"></i>
                  <% end %></li>
                <li><%= link_to teacher, confirm: 'Вы уверены?', method: :delete do %>
                      <i class="icon-trash"></i>
                  <% end %></li>
            <% end %>
          </ul>
        </td>
        <td><%= teacher.fio %></td>
        <td><%= teacher.phone %></td>
        <td>
          <% teacher.courses.each do |x| %>
              <%=  x.name + ", " %>
          <% end %>
        </td>
        <td><%= teacher.email %></td>
        <td><%= teacher.idvk %></td>
        <td><%= teacher.workplace %></td>
        <td><%= teacher.comment %></td>
        <td><%= teacher.salary %></td>
        <td><%= teacher.percent %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<!-- Modal -->
<%= set_modal_window %>
<script>
    var delay = (function(){
        var timer = 0;
        return function(callback, ms){
            clearTimeout (timer);
            timer = setTimeout(callback, ms);
        };
    })();
    $(document).ready(function() {
        var res=0;
        $('.tr').each(function(){
            if ( getComputedStyle(this,null).display != "none") {
                res += 1;
            }
        });
        $('#result').text(res);

        $('input').keyup(function() {
            delay(function(){
                var res=0;
                $('.tr').each(function(){
                    if ( getComputedStyle(this,null).display != "none") {
                        res += 1;
                    }
                });
                $('#result').text(res);
            }, 350 );
        });

    });

</script>

app/views/teachers/index.js.erb
$('#myModalLabel').html("Преподаватель");
$('.modal-body p').html("<%=j render partial: 'modal' %>");

app/views/teachers/new.html.erb
<%= render 'form' %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>фамилия:</b>
  <%= @teacher.surname %>
</p>
<p>
  <b>имя:</b>
  <%= @teacher.name %>
</p>

<p>
  <b>телефон:</b>
  <%= @teacher.phone %>
</p>

<p>
  <b>Email:</b>
  <%= @teacher.email %>
</p>

<p>
  <b>Id-vk:</b>
  <%= @teacher.idvk %>
</p>

<p>
  <b>рабочее место:</b>
  <%= @teacher.workplace %>
</p>

<p>
  <b>коммент:</b>
  <%= @teacher.comment %>
</p>

<p>
  <b>курсы:</b>
  <% @teacher.courses.each do |x| %>
    <%=  x.name + ", " %>
  <% end %>
</p>

<p>
  <b>оклад:</b>
  <%= @teacher.salary %>
</p>

<p>
  <b>оклад:</b>
  <%= @teacher.percent %>
</p>



<%= link_to 'редактировать', edit_teacher_path(@teacher) %> |
<%= link_to 'к списку', teachers_path %>

app/views/teachers/teachers_to_excel_format.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:x="urn:schemas-microsoft-com:office:excel"
          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">имя</Data></Cell>
        <Cell><Data ss:Type="String">телефон</Data></Cell>
        <Cell><Data ss:Type="String">курсы</Data></Cell>
        <Cell><Data ss:Type="String">email</Data></Cell>
        <Cell><Data ss:Type="String">vk(id)</Data></Cell>
        <Cell><Data ss:Type="String">место работы</Data></Cell>
        <Cell><Data ss:Type="String">коментарий</Data></Cell>
        <Cell><Data ss:Type="String">оклад</Data></Cell>
        <Cell><Data ss:Type="String">процент</Data></Cell>
        <Cell><Data ss:Type="String">создано</Data></Cell>
        <Cell><Data ss:Type="String">отредактировано</Data></Cell>
      </Row>
      <% @teachers.each do |teacher| %>
          <Row>
            <Cell><Data ss:Type="Number"><%= teacher.id %></Data></Cell>
            <Cell><Data ss:Type="String"><%= teacher.fio%></Data></Cell>
            <Cell><Data ss:Type="String"><%= teacher.phone %></Data></Cell>
            <Cell><Data ss:Type="String">
              <% teacher.courses.each do |x| %>
                  <%=  x.name + ", " %>
              <% end %>
            </Data></Cell>
            <Cell><Data ss:Type="String"><%= teacher.email %></Data></Cell>
            <Cell><Data ss:Type="String"><%= teacher.idvk %></Data></Cell>
            <Cell><Data ss:Type="String"><%= teacher.workplace %></Data></Cell>
            <Cell><Data ss:Type="String"><%= teacher.comment %></Data></Cell>
            <Cell><Data ss:Type="Number"><%= teacher.salary %></Data></Cell>
            <Cell><Data ss:Type="Number"><%= teacher.percent %></Data></Cell>
            <Cell><Data ss:Type="String"><%= teacher.created_at %></Data></Cell>
            <Cell><Data ss:Type="String"><%= teacher.updated_at %></Data></Cell>
          </Row>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>