config/routes.rb
Reports::Application.routes.draw do

  get "help/index"

  get "orders/payment"
  get "clients/clients_to_excel_format"
  get "orders/orders_to_excel_format"
  get "outlays/outlays_to_excel_format"
  get "salaries/salaries_to_excel_format"
  get "msalaries/msalaries_to_excel_format"
  get "payments/payments_to_excel_format"
  get "statuses/statuses_to_excel_format"
  get "resources/districts_to_excel_format"
  get "channels/channels_to_excel_format"
  get "courses/courses_to_excel_format"
  get "costs/costs_to_excel_format"
  get "offices/offices_to_excel_format"
  get "managers/managers_to_excel_format"
  get "teachers/teachers_to_excel_format"
  get "schedules/schedules_to_excel_format"
  get "objects_of_expenditures/obj_of_expend_to_excel_format"

  post "clients/sort_options"
  post "orders/sort_options"
  post "outlays/sort_options"
  post "salaries/sort_options"
  post "msalaries/sort_options"
  post "payments/sort_options"
  post "salaries/:id/edit" => 'salaries#edit'
  post "salaries/:id/schedules" => 'salaries#schedules'
  post "payments/new"
  post "salaries/new"

  post "salaries/salary_search_options"
  post "/salary_search_options" =>  'salaries#salary_search_options'
  post "salaries/:id/salary_search_options" => 'salaries#salary_search_options'

  post "orders/search_optionss"
  post "/search_optionss" =>  'orders#search_optionss'
  post "orders/:id/search_optionss" => 'orders#search_optionss'

  post "payments/search_options"
  post "/search_options" =>  'payments#search_options'
  post "payments/:id/search_options" => 'payments#search_options'

  resources :outlays

  resources :msalaries

  resources :managers

  resources :salaries

  resources :teachers

  resources :schedules

  resources :payments

  resources :orders

  resources :offices

  resources :clients

  resources :costs

  resources :courses

  resources :channels

  resources :resources

  resources :help

  resources :objects_of_expenditures

  resources :mail_boxes

  resources :periods

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :users do 
    member do
      get 'change_user'
      get 'ban'
    end

    collection do
      get 'list'
    end
  end

  resources :statuses
  match 'orders/payment', to: 'orders#payment', as: :payment_to_order
  match 'clients/clients_to_excel_format', to: 'clients#clients_to_excel_format', as: :clients_to_xls
  match 'orders/orders_to_excel_format', to: 'orders#orders_to_excel_format', as: :orders_to_xls
  match 'outlays/outlays_to_excel_format', to: 'outlays#outlays_to_excel_format', as: :outlays_to_xls
  match 'salaries/salaries_to_excel_format', to: 'salaries#salaries_to_excel_format', as: :salaries_to_xls
  match 'msalaries/msalaries_to_excel_format', to: 'msalaries#msalaries_to_excel_format', as: :msalaries_to_xls
  match 'payments/payments_to_excel_format', to: 'payments#payments_to_excel_format', as: :payments_to_xls
  match 'statuses/statuses_to_excel_format', to: 'statuses#statuses_to_excel_format', as: :statuses_to_xls
  match 'resources/resources_to_excel_format', to: 'resources#resources_to_excel_format', as: :resources_to_xls
  match 'channels/channels_to_excel_format', to: 'channels#channels_to_excel_format', as: :channels_to_xls
  match 'courses/courses_to_excel_format', to: 'courses#courses_to_excel_format', as: :courses_to_xls
  match 'costs/costs_to_excel_format', to: 'costs#costs_to_excel_format', as: :costs_to_xls
  match 'offices/offices_to_excel_format', to: 'offices#offices_to_excel_format', as: :offices_to_xls
  match 'managers/managers_to_excel_format', to: 'managers#managers_to_excel_format', as: :managers_to_xls
  match 'teachers/teachers_to_excel_format', to: 'teachers#teachers_to_excel_format', as: :teachers_to_xls
  match 'schedules/schedules_to_excel_format', to: 'schedules#schedules_to_excel_format', as: :schedules_to_xls
  match 'resources/districts_to_excel_format', to: 'resources#districts_to_excel_format', as: :district_to_xls
  match 'objects_of_expenditures/obj_of_expend_to_excel_format', to: 'objects_of_expenditures#obj_of_expend_to_excel_format', as: :obj_of_expend_to_xls

  match 'help/admin_add_user', to: 'help#admin_add_user', as: :add_user

  match 'users/create', to: 'users#create', as: :create_user

  match 'help', to: 'help#index', as: :help_page

  root :to => 'clients#index'

end

app/views/resources/_form.html.erb
<div class="form-wrap clearfix">
  <h1><%= action_name == 'edit' ? 'Редактирование источника' : 'Новый источник'%></h1>
  <hr>
  <%= flash[:notice]%>
<%= simple_form_for(@resource) do |f| %>

    <%= f.input :name, label: "Название" %>
    <div id="submit">
      <%= f.button :submit, :value => "Сохранить"%>
      <div>
        <%= link_to 'К списку', resources_path, class: "btn"%>
      </div>
    </div>

<% end %>
</div>

app/views/resources/_modal.html.erb
<p>
  <b>Название:</b>
  <%= @resource.name %>
</p>

app/views/resources/districts_to_excel_format.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:x="urn:schemas-microsoft-com:office:excel"
          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">название</Data></Cell>
        <Cell><Data ss:Type="String">дата создания</Data></Cell>
        <Cell><Data ss:Type="String">дата обновления</Data></Cell>
      </Row>
      <% @resources.each do |resource| %>
          <Row>
            <Cell><Data ss:Type="Number"><%= resource.id %></Data></Cell>
            <Cell><Data ss:Type="String"><%= resource.name %></Data></Cell>
            <Cell><Data ss:Type="String"><%= resource.created_at.strftime("%d.%m.%Y") %></Data></Cell>
            <Cell><Data ss:Type="String"><%= resource.updated_at.strftime("%d.%m.%Y") %></Data></Cell>
          </Row>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/resources/edit.html.erb
<%= render 'form' %>

app/views/resources/index.html.erb
<div class='table-actions'>
  <h1 class='page-title'>Источники</h1>
  <ul class='create-download'>
    <% if user_role != "visitor" %>
        <li>
          <%= link_to new_resource_path do %>
              <i class='icon-plus-sign icon-2x'></i>
          <% end %>
        </li>
    <% end %>
    <li>
      <%= link_to district_to_xls_path + ".xls" do %>
          <i class='icon-save icon-2x'></i>
      <% end %>
    </li>
  </ul>
  <% if flash[:notice] %>
      <span style="color: #41b140;"><%= flash[:notice] %></span>
  <% end %>
  <hr>
  <%= paginate @resources, :window => 2 %>
</div>
<table id="demotable" class="table table-striped">
  <thead>
  <tr class="sort">
    <th class='record-manipulate'></th>
    <th>Название</th>
  </tr>
  </thead>
  <tbody>
<% @resources.each do |resource| %>
  <tr>
    <td class="manipulate-box">
      <ul>
        <li><%= link_to url_for(id: resource, anchor: 'myModal'), {:remote => true, 'data-toggle'=>"modal"} do%> <i class="icon-search"></i>
          <% end %></li>
        <% if user_role != "visitor" %>
            <li><%= link_to edit_resource_path(resource) do %> <i class="icon-pencil"></i>
              <% end %></li>
            <li><%= link_to resource, confirm: 'Вы уверены?', method: :delete do %>
                  <i class="icon-trash"></i>
              <% end %></li>
        <% end %>
      </ul>
    </td>
    <td><%= resource.name %></td>
  </tr>
<% end %>
  </tbody>
</table>

<!-- Modal -->
<%= set_modal_window %>

app/views/resources/index.js.erb
$('#myModalLabel').html("Источник");
$('.modal-body p').html("<%=j render partial: 'modal' %>");

app/views/resources/new.html.erb
<%= render 'form' %>

app/views/resources/resources_to_excel_format.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:x="urn:schemas-microsoft-com:office:excel"
          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">название</Data></Cell>
        <Cell><Data ss:Type="String">дата создания</Data></Cell>
        <Cell><Data ss:Type="String">дата обновления</Data></Cell>
      </Row>
      <% @resources.each do |resource| %>
          <Row>
            <Cell><Data ss:Type="Number"><%= resource.id %></Data></Cell>
            <Cell><Data ss:Type="String"><%= resource.name %></Data></Cell>
            <Cell><Data ss:Type="String"><%= resource.created_at.strftime("%d.%m.%Y") %></Data></Cell>
            <Cell><Data ss:Type="String"><%= resource.updated_at.strftime("%d.%m.%Y") %></Data></Cell>
          </Row>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>название:</b>
  <%= @resource.name %>
</p>


<%= link_to 'редактировать', edit_resource_path(@resource) %> |
<%= link_to 'к списку', resources_path %>